{
  "openapi": "3.0.0",
  "info": {
    "title": "prod - hubApp",
    "description": "Production url endpoints",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://archi-hub-backend.vercel.app",
      "variables": {}
    }
  ],
  "paths": {
    "/auth/completeSignUp/{token}": {
      "get": {
        "tags": ["Misc"],
        "summary": " link sent to email to complete signup",
        "operationId": "clickToCompleteSignUp",
        "parameters": [
          {
            "name": "token",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{signUpToken}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/resetPassword/setNewPassword": {
      "post": {
        "tags": ["passwordReset"],
        "summary": "setNewPassword",
        "operationId": "setNewPassword",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/setNewPasswordRequest"
                  },
                  {
                    "example": {
                      "newPassword": "mike"
                    }
                  }
                ]
              },
              "example": {
                "newPassword": "mike"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/resetPassword/createToken": {
      "post": {
        "tags": ["passwordReset"],
        "summary": "resetPassword",
        "operationId": "resetPassword",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/resetPasswordRequest"
                  },
                  {
                    "example": {
                      "email": "farindemoses@gmail.com"
                    }
                  }
                ]
              },
              "example": {
                "email": "farindemoses@gmail.com"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/auth/register": {
      "post": {
        "tags": ["auth"],
        "summary": "register",
        "operationId": "register",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/registerrequest"
                  },
                  {
                    "example": {
                      "userName": "Mhyke",
                      "firstName": "Mhyke",
                      "lastName": "Mhyke",
                      "interests": ["3D", "rendering", "archviz"]
                    }
                  }
                ]
              },
              "example": {
                "userName": "Mhyke",
                "firstName": "Mhyke",
                "lastName": "Mhyke",
                "interests": ["3D", "rendering", "archviz"]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/auth/preSignUp": {
      "post": {
        "tags": ["auth"],
        "summary": "presignUp",
        "operationId": "presignUp",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/presignUpRequest"
                  },
                  {
                    "example": {
                      "email": "micheal.badmus@gmail.com",
                      "password": "Mhyke"
                    }
                  }
                ]
              },
              "example": {
                "email": "micheal.badmus@gmail.com",
                "password": "Mhyke"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/auth/login": {
      "post": {
        "tags": ["auth"],
        "summary": "login",
        "operationId": "login",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/loginrequest"
                  },
                  {
                    "example": {
                      "email": "micheal.badmus@gmail.com",
                      "password": "Mhyke"
                    }
                  }
                ]
              },
              "example": {
                "email": "micheal.badmus@gmail.com",
                "password": "Mhyke"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/jobs/getAllJobs": {
      "get": {
        "tags": ["jobs"],
        "summary": "getAllJobs",
        "operationId": "getAllJobs",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/jobs/postJob": {
      "post": {
        "tags": ["jobs"],
        "summary": "createJob",
        "operationId": "createJob",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/createJobRequest"
                  },
                  {
                    "example": {
                      "description": "i need a graphics designer to work his ass off",
                      "location": "lagos mainland",
                      "tags": "renderingGraphicsdesign"
                    }
                  }
                ]
              },
              "example": {
                "description": "i need a graphics designer to work his ass off",
                "location": "lagos mainland",
                "tags": "renderingGraphicsdesign"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/jobs/updateJob/{jobID}": {
      "patch": {
        "tags": ["jobs"],
        "summary": "updateJob",
        "operationId": "updateJob",
        "parameters": [
          {
            "name": "jobID",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "645f842379e08a4913ec001c"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/updateJobRequest"
                  },
                  {
                    "example": {
                      "location": "surulere"
                    }
                  }
                ]
              },
              "example": {
                "location": "surulere"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/jobs/reactToJob/{jobID}": {
      "patch": {
        "tags": ["jobs"],
        "summary": "reactToJob",
        "operationId": "reactToJob",
        "parameters": [
          {
            "name": "jobID",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "645f835a7d15b93c27f16343"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/jobs/getUser/{ID}": {
      "get": {
        "tags": ["jobs"],
        "summary": "getOneUser",
        "operationId": "getOneUser",
        "parameters": [
          {
            "name": "ID",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "6465ba12b86eee1eeaa835ad"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/jobs/deleteJob/{jobID}": {
      "delete": {
        "tags": ["jobs"],
        "summary": "deleteJob",
        "operationId": "deleteJob",
        "parameters": [
          {
            "name": "jobID",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "645f835a7d15b93c27f16343"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "presignUpRequest": {
        "title": "presignUpRequest",
        "required": ["email", "password"],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "email": "micheal.badmus@gmail.com",
          "password": "Mhyke"
        }
      },
      "loginrequest": {
        "title": "loginrequest",
        "required": ["email", "password"],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "email": "micheal.badmus@gmail.com",
          "password": "Mhyke"
        }
      },
      "registerrequest": {
        "title": "registerrequest",
        "required": ["userName", "firstName", "lastName", "interests"],
        "type": "object",
        "properties": {
          "userName": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "interests": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          }
        },
        "example": {
          "userName": "Mhyke",
          "firstName": "Mhyke",
          "lastName": "Mhyke",
          "interests": ["3D", "rendering", "archviz"]
        }
      },
      "updateJobRequest": {
        "title": "updateJobRequest",
        "required": ["location"],
        "type": "object",
        "properties": {
          "location": {
            "type": "string"
          }
        },
        "example": {
          "location": "surulere"
        }
      },
      "createJobRequest": {
        "title": "createJobRequest",
        "required": ["description", "location", "tags"],
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "location": {
            "type": "string"
          },
          "tags": {
            "type": "string"
          }
        },
        "example": {
          "description": "i need a graphics designer to work his ass off",
          "location": "lagos mainland",
          "tags": "renderingGraphicsdesign"
        }
      },
      "resetPasswordRequest": {
        "title": "resetPasswordRequest",
        "required": ["email"],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          }
        },
        "example": {
          "email": "farindemoses@gmail.com"
        }
      },
      "setNewPasswordRequest": {
        "title": "setNewPasswordRequest",
        "required": ["newPassword"],
        "type": "object",
        "properties": {
          "newPassword": {
            "type": "string"
          }
        },
        "example": {
          "newPassword": "mike"
        }
      }
    },
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "security": [],
  "tags": [
    {
      "name": "Misc",
      "description": ""
    },
    {
      "name": "passwordReset",
      "description": ""
    },
    {
      "name": "auth",
      "description": ""
    },
    {
      "name": "jobs",
      "description": ""
    }
  ]
}
